# Warning
- color: "ee0701"
  description: "Categorize bug reports."- color: "ee0701"
  description: "Categorize vulnerability reports."- color: "0e8a16"
  description: "Good for newcomers."- color: "0e8a16"
  description: "Extra attention is needed."- color: "b60205"
  description: "This issue or pull request already exists."- color: "b60205"
  description: "This will not be worked on."- color: "cfd3d7"
  description: "Extra Small size issue or PR."- color: "cfd3d7"
  description: "Small size issue or PR."- color: "cfd3d7"
  description: "Medium size issue or PR."- color: "cfd3d7"
  description: "Large size issue or PR."- color: "cfd3d7"
  description: "Extra Large size issue or PR."- color: "fbca04"
  description: "This issue or pull request is related to account module."
  name: ":floppy_disk: account"
- color: "fbca04"
  description: "This issue or pull request is related to data-source module."
  name: ":floppy_disk: data-source"
- color: "fbca04"
  description: "This issue or pull request is related to data-set module."
  name: ":floppy_disk: data-set"
- color: "fbca04"
  description: "This issue or pull request is related to folder module."
  name: ":floppy_disk: folder"
- color: "fbca04"
  description: "This issue or pull request is related to group module."
  name: ":floppy_disk: group"
- color: "fbca04"
  description: "This issue or pull request is related to namespace module."
  name: ":floppy_disk: namespace"
- color: "fbca04"
  description: "This issue or pull request is related to user module."
  name: ":floppy_disk: user"
- color: "fbca04"
  description: "This issue or pull request is related to vpc-connection module."
  name: ":floppy_disk: vpc-connection"

