# Modules
- color: "fbca04"
  description: "This issue or pull request is related to account module."
  name: ":floppy_disk: account"
- color: "fbca04"
  description: "This issue or pull request is related to data-set module."
  name: ":floppy_disk: data-set"
- color: "fbca04"
  description: "This issue or pull request is related to data-source module."
  name: ":floppy_disk: data-source"
- color: "fbca04"
  description: "This issue or pull request is related to folder module."
  name: ":floppy_disk: folder"
- color: "fbca04"
  description: "This issue or pull request is related to group module."
  name: ":floppy_disk: group"
- color: "fbca04"
  description: "This issue or pull request is related to namespace module."
  name: ":floppy_disk: namespace"
- color: "fbca04"
  description: "This issue or pull request is related to user module."
  name: ":floppy_disk: user"
- color: "fbca04"
  description: "This issue or pull request is related to vpc-connection module."
  name: ":floppy_disk: vpc-connection"
