# Modules
":floppy_disk: account":
- changed-files:
  - any-glob-to-any-file:
    - modules/account/**/*

":floppy_disk: data-source":
- changed-files:
  - any-glob-to-any-file:
    - modules/data-source/**/*

":floppy_disk: folder":
- changed-files:
  - any-glob-to-any-file:
    - modules/folder/**/*

":floppy_disk: group":
- changed-files:
  - any-glob-to-any-file:
    - modules/group/**/*

":floppy_disk: namespace":
- changed-files:
  - any-glob-to-any-file:
    - modules/namespace/**/*

":floppy_disk: user":
- changed-files:
  - any-glob-to-any-file:
    - modules/user/**/*

":floppy_disk: vpc-connection":
- changed-files:
  - any-glob-to-any-file:
    - modules/vpc-connection/**/*
